import os
import re
from fpdf import FPDF
from fpdf.enums import XPos, YPos

class LiftyPremiumPDF(FPDF):
    def __init__(self, title_text="LIFTY OS: TRAINING PLAN"):
        super().__init__()
        # Premium Color Palette
        self.brand_dark = (15, 23, 42)      # Slate 900
        self.brand_accent = (56, 189, 248)  # Light Blue 400
        self.brand_gray = (100, 116, 139)   # Slate 500
        self.brand_light = (241, 245, 249)  # Slate 100
        self.text_main = (30, 41, 59)       # Slate 800
        self.text_muted = (71, 85, 105)     # Slate 600
        
        self.title_text = title_text
        self.set_margins(15, 20, 15)

    def header(self):
        # Full width dark header banner
        self.set_fill_color(*self.brand_dark)
        self.rect(0, 0, 210, 35, 'F')
        
        # Accent line
        self.set_fill_color(*self.brand_accent)
        self.rect(0, 35, 210, 2, 'F')
        
        # Title Text
        self.set_y(12)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 22)
        self.cell(0, 10, self.title_text, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.brand_accent)
        self.cell(0, 6, "EVIDENCE-BASED AUTOREGULATED PROGRAMMING", align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Reset Y below header
        self.set_y(45)

    def footer(self):
        self.set_y(-20)
        # Subtle top border for footer
        self.set_draw_color(*self.brand_light)
        self.line(15, self.get_y(), 195, self.get_y())
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*self.brand_gray)
        self.cell(0, 10, f'Generated by Lifty OS | Page {self.page_no()}/{{nb}}', align='C')

    def render_metadata(self, metadata):
        self.set_fill_color(*self.brand_light)
        self.set_draw_color(226, 232, 240)
        
        # Draw a nice box
        y_start = self.get_y()
        self.rect(15, y_start, 180, len(metadata) * 8 + 6, style='DF')
        
        self.set_y(y_start + 3)
        for key, val in metadata.items():
            self.set_x(20)
            self.set_font('Helvetica', 'B', 10)
            self.set_text_color(*self.text_main)
            self.cell(35, 8, f"{key}:", align='L')
            
            self.set_font('Helvetica', '', 10)
            if "MANDATORY DELOAD" in val or "Fatigue" in val or "-" in val:
                self.set_text_color(220, 38, 38) # Red for alerts
            else:
                self.set_text_color(*self.text_muted)
            self.cell(140, 8, val, align='L', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        self.set_y(self.get_y() + 8)

    def section_header(self, title):
        self.ln(5)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*self.brand_dark)
        self.cell(0, 8, title.upper(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Subtle underline
        y = self.get_y()
        self.set_draw_color(*self.brand_gray)
        self.set_line_width(0.3)
        self.line(15, y, 195, y)
        self.ln(4)

    def render_text_block(self, lines):
        self.set_font('Helvetica', '', 11)
        self.set_text_color(*self.text_main)
        for line in lines:
            # Handle bold formatting in simple text
            line = line.replace('**', '')
            self.multi_cell(180, 6, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(3)

    def render_callout_box(self, title, items):
        # Calculate estimated height (allowing some wrap)
        h = 10 + (len(items) * 7) + 6
        
        # Check if the callout box fits on the current page. If not, add page first.
        if self.get_y() + h > self.page_break_trigger:
            self.add_page()
            
        self.ln(3)
        self.set_fill_color(254, 242, 242) # Very light red/orange for rules
        self.set_draw_color(252, 165, 165)
        self.set_line_width(0.5)
        
        start_page = self.page_no()
        y_start = self.get_y()
        self.rect(15, y_start, 180, h, style='DF')
        
        self.set_y(y_start + 4)
        self.set_x(20)
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(153, 27, 27) # Dark red
        self.cell(0, 6, title.upper(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.text_main)
        for item in items:
            self.set_x(20)
            item_clean = item.replace('**', '')
            self.multi_cell(170, 6, item_clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Use relative offset to avoid vertical coordinate jumps if a page break happened.
        # If we are on the same page, ensure we clear the drawn rectangle height.
        if self.page_no() == start_page:
            self.set_y(max(self.get_y() + 6, y_start + h + 5))
        else:
            self.set_y(self.get_y() + 6)

    def render_workout_table(self, title, items):
        self.ln(5)
        
        # Table Header
        self.set_fill_color(*self.brand_dark)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 12)
        # Rounded header look by just coloring the cell
        self.cell(180, 10, f"  {title.upper()}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Column Headers
        self.set_fill_color(*self.brand_gray)
        self.set_font('Helvetica', 'B', 9)
        self.cell(50, 7, "  EXERCISE", fill=True, align='L')
        self.cell(35, 7, "PRESCRIPTION", fill=True, align='C')
        self.cell(75, 7, "NOTES", fill=True, align='L')
        self.cell(20, 7, "VOL", fill=True, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Rows
        self.set_font('Helvetica', '', 9)
        self.set_draw_color(226, 232, 240)
        
        fill = False
        self.set_fill_color(*self.brand_light)
        
        for item in items:
            self.set_text_color(*self.text_main)
            # Parse the item string: - **Exercise Name:** Prescription (Notes). [Volume: X]
            # It might vary, so we use regex or splits
            
            # Extract volume if present
            vol_match = re.search(r'\[Volume:\s*(.*?)\]', item)
            vol_str = vol_match.group(1) if vol_match else ""
            item_clean = re.sub(r'\s*\[Volume:.*?\]', '', item)
            
            # Extract exercise name
            ex_match = re.search(r'\*\*(.*?)\*\*(.*)', item_clean)
            if ex_match:
                ex_name = ex_match.group(1).replace(':', '').strip()
                remainder = ex_match.group(2).strip()
            else:
                ex_name = ""
                remainder = item_clean.strip('- ').strip()
                
            # Try to split remainder into prescription and notes based on parentheses or '@'
            notes_match = re.search(r'\((.*?)\)', remainder)
            notes_str = notes_match.group(1) if notes_match else ""
            rx_str = re.sub(r'\(.*?\)', '', remainder).strip(': ').strip()
            
            # Save position
            start_y = self.get_y()
            
            # Calculate max height needed for this row
            self.set_font('Helvetica', 'B', 9)
            ex_lines = len(self.multi_cell(50, 6, ex_name, dry_run=True, output="LINES"))
            self.set_font('Helvetica', '', 9)
            notes_lines = len(self.multi_cell(75, 6, notes_str, dry_run=True, output="LINES"))
            rx_lines = len(self.multi_cell(35, 6, rx_str, dry_run=True, output="LINES"))
            
            max_lines = max(ex_lines, notes_lines, rx_lines, 1)
            row_height = max_lines * 6
            
            # Check page break
            if self.get_y() + row_height > self.page_break_trigger:
                self.add_page()
                start_y = self.get_y()
            
            # Draw cells
            # Exercise
            self.set_font('Helvetica', 'B', 9)
            self.set_xy(15, start_y)
            self.rect(15, start_y, 180, row_height, style='F' if fill else '')
            self.multi_cell(50, 6, ex_name, border=0)
            
            # Prescription
            self.set_font('Helvetica', '', 9)
            self.set_xy(65, start_y)
            self.multi_cell(35, 6, rx_str, align='C', border=0)
            
            # Notes
            self.set_text_color(*self.text_muted)
            self.set_xy(100, start_y)
            self.multi_cell(75, 6, notes_str, border=0)
            
            # Volume
            self.set_text_color(*self.text_main)
            self.set_font('Helvetica', 'B', 9)
            self.set_xy(175, start_y)
            self.multi_cell(20, row_height, vol_str, align='C', border=0)
            
            # Move Y to next row
            self.set_y(start_y + row_height)
            
            # Subtle bottom border for row
            self.set_draw_color(226, 232, 240)
            self.line(15, self.get_y(), 195, self.get_y())
            
            fill = not fill
            
        self.ln(5)


def parse_and_generate(md_path, pdf_path):
    with open(md_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    title = "LIFTY OS: TRAINING PLAN"
    metadata = {}
    sections = []
    
    current_section = None
    
    for line in lines:
        line = line.strip()
        if not line or line == '---':
            continue
            
        if line.startswith('# '):
            title = line[2:].strip()
            continue
            
        # Check for metadata
        meta_match = re.match(r'\*\*(.*?)\*\*\s*(.*)', line)
        if meta_match and not current_section:
            key = meta_match.group(1).replace(':', '').strip()
            val = meta_match.group(2).strip()
            metadata[key] = val
            continue
            
        # Check for section headers
        if line.startswith('## '):
            if current_section:
                sections.append(current_section)
            current_section = {
                'type': 'generic',
                'title': line[3:].strip(),
                'content': []
            }
            if current_section['title'].lower().startswith('workout'):
                current_section['type'] = 'workout'
            continue
            
        if line.startswith('### '):
            if current_section:
                sections.append(current_section)
            current_section = {
                'type': 'callout',
                'title': line[4:].strip(),
                'content': []
            }
            continue
            
        if current_section:
            current_section['content'].append(line)

    if current_section:
        sections.append(current_section)
        
    def sanitize(text):
        replacements = {
            '–': '-', '—': '-', '‘': "'", '’': "'", '“': '"', '”': '"', '…': '...', '•': '*'
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text

    # Generate PDF
    pdf = LiftyPremiumPDF(sanitize(title))
    pdf.alias_nb_pages()
    pdf.add_page()
    
    if metadata:
        sanitized_metadata = {sanitize(k): sanitize(v) for k, v in metadata.items()}
        pdf.render_metadata(sanitized_metadata)
        
    for sec in sections:
        sec_title = sanitize(sec['title'])
        if sec['type'] == 'generic':
            pdf.section_header(sec_title)
            # separate list items from regular text
            text_block = []
            list_block = []
            for item in sec['content']:
                item = sanitize(item)
                if item.startswith('- ') or re.match(r'^\d+\.', item):
                    list_block.append(item)
                else:
                    text_block.append(item)
            if text_block:
                pdf.render_text_block(text_block)
            if list_block:
                pdf.render_text_block(list_block)
                
        elif sec['type'] == 'callout':
            sanitized_content = [sanitize(item) for item in sec['content']]
            pdf.render_callout_box(sec_title, sanitized_content)
            
        elif sec['type'] == 'workout':
            sanitized_content = [sanitize(item) for item in sec['content']]
            pdf.render_workout_table(sec_title, sanitized_content)
            
    pdf.output(pdf_path)

if __name__ == "__main__":
    # Calculate base directory relative to this script (up one directory from 'scripts/')
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    md_file = os.path.join(base_dir, 'training_plans', 'active_plan.md')
    pdf_file = os.path.join(base_dir, 'training_plans', 'active_plan.pdf')
    
    if os.path.exists(md_file):
        try:
            parse_and_generate(md_file, pdf_file)
            print(f"Premium PDF generated: {pdf_file}")
        except Exception as e:
            print(f"Error generating PDF: {str(e)}")
    else:
        print("Error: active_plan.md not found.")
